# Local dev defaults; overridden by env vars injected by docker-compose in production
# For Docker: uses 'db' service hostname. For local: uses localhost
# override with env via docker-compose)  , later change to aws rds endpoint
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/employeedb} 

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Programming.in1@}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
